#!/usr/bin/env ruby

require 'i3ipc'

def suppress_output
  original_stderr = $stderr.clone
  original_stdout = $stdout.clone

  $stderr.reopen(File.new('/dev/null', 'w'))
  $stdout.reopen(File.new('/dev/null', 'w'))

  yield
ensure
  $stdout.reopen(original_stdout)
  $stderr.reopen(original_stderr)
end

i3 = nil

suppress_output do
  i3 = I3Ipc::Connection.new
end

if ARGV.empty?
  workspaces = i3.workspaces.map(&:to_h).map{|w| w[:num]}.map{|w| "workspace #{w}"}
  puts workspaces
else
  workspace = ARGV.first
  fail unless workspace.start_with?("workspace")
  workspace = workspace.split(" ").last.to_i
  i3.command("workspace #{workspace}")
end

i3.close
