#!/usr/bin/env bash

# helper script for systemd units

set -e
set -o pipefail

if ! test -d .git
then
  echo "not '.git' directory found"
  exit 1
fi

branch=$(git rev-parse --abbrev-ref HEAD)
if test $? -ne 0
then
  echo "failed to get current branch"
  exit 2
fi

if test $branch != "master"
then
  echo "not on 'master' branch, doing nothing"
  exit 0
fi

if ! test -z "$(git status --porcelain)"
then
  echo "not clean, doing nothing"
  exit 0
fi

git pull
