#!/bin/bash

# manage locking of screen, in particular make
# sure transparency does not defeat the locking

set -o pipefail
set -e

TRANSPARENCY_SERVICE=sway-inactive-transparency

systemctl --user stop $TRANSPARENCY_SERVICE
swaylock --ignore-empty-password --show-failed-attempts --indicator-caps-lock --color='000000'
systemctl --user start $TRANSPARENCY_SERVICE
