#!/bin/bash

systemctl --user --quiet is-active picom
picom_active=$?

if [[ ${picom_active} == 0 ]]
then
  systemctl --user stop picom
fi

mpc pause
/usr/bin/pactl set-sink-mute @DEFAULT_SINK@ 1

env -i DISPLAY=${DISPLAY} XAUTHORITY=${XAUTHORITY} slock &
slock_pid=$!

if [[ -e /dev/fd/${XSS_SLEEP_LOCK_FD:--1} ]]; then
  exec {XSS_SLEEP_LOCK_FD}<&-
fi

wait ${slock_pid}

systemctl --user restart pulseaudio

if [[ ${picom_active} == 0 ]]
then
  systemctl --user start picom
fi
