#!/usr/bin/env bash

# manage locking of screen, in particular make
# sure transparency does not defeat the locking

set -o pipefail
set -o errexit

systemctl --user stop inactive-transparency
swaylock --ignore-empty-password --show-failed-attempts --indicator-caps-lock --color='000000'
systemctl --user start inactive-transparency
